### ISSUE TITLE
How to specify more options?

### ISSUE THREAD

**Issue by shinebayar-g** [ShaunLWM/node-compress-image-cli#3]
Hi, first of all thanks for the cli it was much needed.

According to [API](https://github.com/semiromid/compress-images#api) we can specify input extensions, engine specific options such as `-trim`, `-progressive`, `-quality` etc. How can we specify these options?

**Comment by ShaunLWM** [comment]
I'll take a look into it and see what I can do by the end of this week. I realized how badly this was coded as well.

**Comment by ShaunLWM** [comment]
v0.0.4 released. Dirty workaround.

```
compress --input "C:/MyPics/" --output "C:/MyPicsCompressed/" --enginejpg "jpegtran" --jpgopts "-trim -progressive -copy none -optimize"
```
